### PR TITLE
Added Mock structure and input output structure of the game

### PR DESCRIPTION
**Pull request by angel-mora**
## Milestone 2: User Interface

Content in main.rb file
Dialogue through gets.chomp and example of interface
We used:
- puts/print
- get.chomp
- mock the basic flow of the game
- executable file

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, but there are a few more things required. 
### The Game Behaviour
* [ ] The application does  not allow a player to move into an occupied position
* [ ] The application does not exit due to invalid input - it informs player about it and asks for their move again
* [ ] The application saves players move and displays status of board after that.
* [ ] The application can determine if move is a winning move
  * [ ] The application can detect a sequence of three horizontal elements that are equal
  * [ ] The application can detect a sequence of three vertical elements that are equal
  * [ ] The application can detect a sequence of three equal elements in a diagonal from left and right to right
* [ ] The application can tell if there was a draw after players move
* [ ] The application can change active player
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @angel-mora and @AdedayoOpeyemi 
### You have done well so far :clap: However, you need to make some adjustments before your project could be approved.
- It is good practice to break a logic like this into different modules, for example, you can have player logic, board logic, game logic in their own different files in the lib folder and call them in the main file
- Your game still misses some functionalities like, it needs to inform me when I enter an invalid value and it needs to be wrapped in a while loop for the game to continue playing until  there is either a win or a draw
### Make all these changes and resubmit for another code review. Good luck.
- Happy coding!

By Raymond
Slack @iamraymond

**Comment by AdedayoOpeyemi** [comment]
Hi Chubi, Hi Raymond

Thanks for your feedback on my ongoing project. However, I am not sure of what the requirement is for the 2nd milestone. A request for a code review on the 3rd milestone was submitted in error. We only intended to submit for the 2nd milestone.

Please can you confirm if we have met the requirement for the 2nd milestone or what I need to do to complete that before submitting a new request?

Thanks

**Comment by Anna-Myzukina** [comment]
# Hi team! :clap: 
### Good job  in Milestone 2 :clap: 
`NOTE` In this step, not everything must work, the point is to make sure that you thought about everything listed below. From [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/). 
screenshot 
### Let me just share what is actually the aim of this milestone. So what are the main steps? :eyes: 

####  Basic game flow is prepared : 

  
  * [ ] `[REQUIRED]` game tells which player turn it is
  * [x] `[REQUIRED]` game asks player to select from available moves
  * [ ] `[REQUIRED]` game informs player if selected move is invalid
  * [ ] `[REQUIRED]` game informs player if selected move is a winning move
  * [ ] `[REQUIRED]` game informs player if selected move is a draw move
  * [ ] `[REQUIRED]` game repeats all actions for next player's move


### [SUGGESTION] The structure of the game's loop should be as follows:

##### Implementation details

* [x] A loop is needed in this game (recommended is `while` but anything else will do) ([OdinProject hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/loop.png))
* [x] Inside loop, you can all actions repeated for each move
* [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:

Using out-of-nowhere numbers to terminate a loop, for example 5.times do ... end is a signal that something is wrong. We recommend the usage of a terminating variable (while game_on) 

### *The final point of this milestone is to make sure that you thought about all the actions needed to play Tic Tac Toe from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work team!
Please take a look at your code again, try running it. You have some syntax errors keeping the game from running. Please attend to them and request a re-review.

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by pelzolga123 — APPROVED** [review]
Approved!

**Comment by pelzolga123** [comment]
## Great work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to development.
_Goodluck in your next milestone_ *Happy coding*

**Pull request merged**
